### PR TITLE
Blogs-Page has been created

### PR DESCRIPTION
**Pull request by Komachian**
A blogs-page has been created in accordance with the template given in Figma

### CODE REVIEW

**Comment by Komachian** [comment]
Video-snippet attached below

https://user-images.githubusercontent.com/75087669/127880203-7fb337a0-70b5-46bf-aed3-b9892fccc534.mp4

**Comment by atm1504** [comment]
@debarghya472 @ankit7das review it.

@pawankumar2002 @HumanChwan peers review first

**Comment by atm1504** [comment]
@debarghya472 @ankit7das review it

@Komachian should we go with a merge of it??

**Comment by Komachian** [comment]
@atm1504 Yes

**Review by debarghya472 — APPROVED** [review]
LGTM!
@Ankit7Das Plz Review

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
