### PR TITLE
Added Carousel

### PR DESCRIPTION
**Pull request by HumanChwan**

### CODE REVIEW

**Comment by atm1504** [comment]
@HumanChwan please attach some screenshots or videos for this

**Comment by HumanChwan** [comment]
@atm1504 It is provided in the screen-snippets folder.

**Comment by atm1504** [comment]
> @atm1504 It is provided in the screen-snippets folder.

@HumanChwan can u drag and drop it here in the comments. Binary files can't be seen that way in Github :)

**Comment by HumanChwan** [comment]
## Summary
   Added Carousel to the hero section of the Home Page.

## 
Please find the attached video.

https://user-images.githubusercontent.com/41588684/127729604-1c163f3c-4257-42ea-8cc3-cef1feb46c66.mp4

**Comment by atm1504** [comment]
@HumanChwan looks fine, can u reposition the ```Publish Your Thought``` and ```Organising Yourself``` exactly as shown in the figma design?

**Comment by HumanChwan** [comment]
Have updated the positioning.

Please find the below attachment.

https://user-images.githubusercontent.com/41588684/127736891-000e121f-ef65-423d-b241-ca3997282297.mp4

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
